$(function(){
	$(".otherinfo .iconp").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight");
	    })
});
$(function(){
    $(".otherinfo .iconp1").bind("touchstart", function(event) {
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight1');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu1").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight1");
        
    })
});
$(function(){
    $(".otherinfo .iconp2").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight2');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu2").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight2");
    })
});
$(function(){
    $(".otherinfo .iconp3").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight3');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu3").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight3");
    })
});
$(function(){
    $(".otherinfo .iconp4").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight4');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu4").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight4");
    })
});
$(function(){
    $(".otherinfo .iconp5").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight5');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu5").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight5");
    })
});
$(function(){
	$(".otherinfo .iconp6").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight6');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu6").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight6");
	    })
});
$(function(){
	$(".otherinfo .iconp7").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight7');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu7").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight7");
	    })
});
$(function(){
	$(".otherinfo .iconp8").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight8');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu8").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight8");
	    })
});
$(function(){
	$(".otherinfo .iconp9").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight9');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu9").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight9");
	})
});
$(function(){
	$(".otherinfo .iconp10").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight10');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu10").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight10");
	    })
});
$(function(){
	$(".otherinfo .iconp11").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight11');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu11").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight11");
	    })
});
$(function(){
	$(".otherinfo .iconp12").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight12');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu12").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight12");
	    })
});
$(function(){
	$(".otherinfo .iconp13").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight14');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu13").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight13");
	    })
});
$(function(){
	$(".otherinfo .iconp14").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight14');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu14").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight14");
	})
});
$(function(){
	$(".otherinfo .iconp15").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight15');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu15").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight15");
	    })
});
$(function(){
	$(".otherinfo .iconp16").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight16');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu16").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight16");
	    })
});
$(function(){
	$(".otherinfo .iconp17").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight17');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu17").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight17");
	    })
});
$(function(){
	$(".otherinfo .iconp18").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight18');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu18").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight18");
	    })
});
$(function(){
	$(".otherinfo .iconp19").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight20");
	    $(".otherinfo").toggleClass('fadeInRight19');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu19").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight19");
	    })
});
$(function(){
	$(".otherinfo .iconp20").bind("touchstart", function(event) {
		$(".otherinfo").removeClass("fadeInRight1");
	    $(".otherinfo").removeClass("fadeInRight2");
	    $(".otherinfo").removeClass("fadeInRight3");
	    $(".otherinfo").removeClass("fadeInRight4");
	    $(".otherinfo").removeClass("fadeInRight5");
	    $(".otherinfo").removeClass("fadeInRight6");
	    $(".otherinfo").removeClass("fadeInRight7");
	    $(".otherinfo").removeClass("fadeInRight8");
	    $(".otherinfo").removeClass("fadeInRight9");
	    $(".otherinfo").removeClass("fadeInRight10");
	    $(".otherinfo").removeClass("fadeInRight11");
	    $(".otherinfo").removeClass("fadeInRight12");
	    $(".otherinfo").removeClass("fadeInRight13");
	    $(".otherinfo").removeClass("fadeInRight14");
	    $(".otherinfo").removeClass("fadeInRight15");
	    $(".otherinfo").removeClass("fadeInRight16");
	    $(".otherinfo").removeClass("fadeInRight17");
	    $(".otherinfo").removeClass("fadeInRight18");
	    $(".otherinfo").removeClass("fadeInRight19");
	    $(".otherinfo").toggleClass('fadeInRight20');
	    event.stopPropagation();
	})
	$(".otherinfo .conmenu20").bind("touchstart", function(event) {
	    event.stopPropagation();
	})
	$(document).bind("touchstart", function() {
	    $(".otherinfo").removeClass("fadeInRight20");
	    })
});